#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#
# IMPORTANT: file gradle-wrapper.jar TIDAK disertakan di paket ini (file binary).
# Android Studio akan otomatis mengunduh & membuatnya saat Anda membuka project ini
# pertama kali (akan muncul prompt "Gradle wrapper not found" -> klik OK/Create).
#
##############################################################################

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

APP_BASE_NAME=$(basename "$0")
APP_HOME=$(cd "$(dirname "$0")" && pwd -P) || exit

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

if ! [ -f "$CLASSPATH" ]; then
    die "ERROR: gradle-wrapper.jar tidak ditemukan.
Buka project ini di Android Studio, biarkan IDE otomatis membuatkan file wrapper yang hilang,
atau jalankan 'gradle wrapper' jika Anda sudah punya instalasi Gradle lain di komputer."
fi

exec java $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
